sigoden/dufs

README.md, assets/index.js, src/args.rs, src/server.rs
=> feat: support webdav

README.md, assets/index.js, src/server.rs
Use drag&drop/webdav to upload folders
=> feat: remove unzip uploaded feature

README.md, src/args.rs, src/server.rs
Now you can mount the server as webdav driver on windows.
=> feat: implement more webdav methods

Cargo.lock, Cargo.toml, src/args.rs, src/main.rs, src/server.rs
=> fix: escape filename

assets/index.css
=> wrote a basic dark theme #15

assets/index.css, assets/index.js, src/server.rs
=> added "Empty folder" text to the page

assets/index.css, assets/index.html, assets/index.js
empty folder got js error
close: #31
=> fix: cannot upload

src/auth.rs, src/main.rs, src/server.rs, tests/http.rs
- refactor status code
- log remote addr and time in miliseconds
=> refactor: trivals changes

src/server.rs, tests/webdav.rs
=> fix: webdav propfind dir with slash

Cargo.lock, Cargo.toml, src/main.rs, src/server.rs, src/streamer.rs, tests/range.rs
=> fix: range request

README.md, src/args.rs, src/server.rs, tests/fixtures.rs, tests/render.rs
=> feat: add option --render-try-index

src/args.rs, src/server.rs, tests/args.rs, tests/bind.rs, tests/fixtures.rs, tests/http.rs
=> feat: serve single file

README.md, src/args.rs, src/server.rs, tests/cors.rs
BREAKING CHANGE: `--cors` rename to `--enable-cors`
=> refactor: rename --cors to --enable-cors

assets/index.css, assets/index.js, src/server.rs
Somebody don't want to display root dirname, so we hidden it.
close #56
=> feat: ui hidden root dirname

assets/index.css, assets/index.html, assets/index.js
Also, I changed the column header from "Date modify" to "Last modified" because that's what `apache2` calls it, and I like it. See also https://w3c.org/icons
=> reactive webpage

Cargo.lock, Cargo.toml, Dockerfile, README.md, src/auth.rs, src/server.rs, tests/args.rs, tests/bind.rs, tests/fixtures.rs, tests/tls.rs
BREAKING CHANGE: rename duf to dufs
=> feat: rename to dufs

assets/index.css, src/args.rs, src/auth.rs, src/server.rs, tests/auth.rs
It's intended for use with TLS.
Also, I have no idea if the tests I copy/pasted pass, because my setup doesn't find the TLS libraries. Sorry
=> added basic auth, and some little css fixes

assets/index.js, src/server.rs
=> fix: escape text contains HTML escape code

Cargo.lock, Cargo.toml, src/logger.rs, src/main.rs, tests/args.rs, tests/bind.rs, tests/fixtures.rs, tests/http.rs
=> feat: use custom logger with timestamp in rfc3339

README.md, src/args.rs, src/server.rs, src/utils.rs, tests/allow.rs, tests/args.rs, tests/assets.rs, tests/fixtures.rs, tests/hidden.rs, tests/http.rs, tests/render.rs, tests/tls.rs, tests/utils.rs
Hide folders from directory listing
```
dufs --hidden .git,.DS_Store
```
close #71
=> feat: add option --hidden to hide folders

Cargo.lock, Cargo.toml, src/server.rs
=> fix: permissions of unzipped files

Cargo.lock, Cargo.toml, src/main.rs, src/server.rs
=> fix: unexpect stack overflow when searching a lot

src/server.rs, tests/render.rs
=> feat: allow search with --render-try-index

assets/index.css, assets/index.html, assets/index.js
=> feat: ui supports creating folder

Cargo.lock, Cargo.toml, src/args.rs, src/main.rs, tests/args.rs, tests/cli.rs
=> feat: add completions

assets/index.js
=> feat: limit the number of concurrent uploads

src/server.rs, tests/cors.rs
=> fix: cors headers

src/args.rs, src/server.rs, tests/args.rs, tests/single_file.rs
=> feat: make --path-prefix works on serving single file

src/auth.rs
=> feat: adjust digest auth timeout to 1day

assets/index.js
=> fix(ui): file path contains special charactors

README.md
Corrected typo in "Advanced topics" heading.
=> Corrected type in README

Cargo.lock, Cargo.toml, assets/index.css, assets/index.html, assets/index.js, src/server.rs, tests/sort.rs, tests/utils.rs
=> feat: support sort by name, mtime, size

src/server.rs, tests/webdav.rs
=> fix: panic on PROPFIND //

README.md, src/args.rs, src/main.rs, src/server.rs, src/unix.rs
bind a unix socket  with `dufs -b /tmp/dufs.socket`
close #141
=> feat: support unix sockets

README.md, assets/index.html, assets/index.js, src/args.rs, src/server.rs, tests/allow.rs, tests/http.rs, tests/render.rs
BREAKING CHANGE: explicitly allow download folder as zip file
=> feat: add option --allow-archive

Cargo.toml, README.md, src/args.rs
=> feat: use env var for args

src/auth.rs, tests/auth.rs
=> fix: remove Method::Options auth check

assets/index.html, assets/index.js
=> fix: clear search input also clear query

Cargo.lock, Cargo.toml, assets/index.css, assets/index.html, assets/index.js, src/server.rs, tests/fixtures.rs, tests/http.rs, tests/render.rs, tests/utils.rs
=> feat: support edit files

Cargo.lock, Cargo.toml, README.md, src/utils.rs
like --hidden '*.abc-cba' matches xyz.abc-cba but do not matches 123.xyz.abc-cba
close #187
=> fix: hidden don't works on some files

assets/index.js
If you open a file with non-UTF8 encoding using the edit button, it may display as garbled text. 
This PR attempts to convert the file into UTF8 encoding for editing.
Supported encoding: https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API/Encodings
=> feat: webui editing support multiple encodings

Cargo.lock, Cargo.toml, src/server.rs, src/utils.rs
=> feat: add timestamp metadata to generated zip file

assets/index.js
There is a js DUFS_MAX_UPLOADINGS variable that controls concurrent uploads.
Users can set this value in the web devtool console.
close #213
=> fix: ui set default max uploading to 1

src/auth.rs, tests/auth.rs
=> fix: auth logic

src/server.rs, tests/cors.rs
=> fix: allow all cors headers and methods

src/auth.rs, src/server.rs, tests/auth.rs
=> fix: webdav only see public folder even logging in

src/server.rs, tests/http.rs
=> fix: search should ignore entry path

src/server.rs
This following the windows explorer.
=> feat: sort by type first, then sort by name/mtime/size

README.md, assets/index.html, src/server.rs, tests/fixtures.rs
=> fix: typo __ASSERTS_PREFIX__

src/server.rs, tests/auth.rs, tests/utils.rs
=> fix: ui readonly if no write perm

assets/index.css, assets/index.html, assets/index.js
=> fix: ui show user-name next to the user-icon

src/server.rs
=> fix: auto delete half-uploaded files

assets/index.css, assets/index.html, assets/index.js, src/server.rs, tests/assets.rs
=> refactor: take improvements from the edge browser

assets/index.css, assets/index.js
=> refactor: ui improve uploading progress

assets/index.css, assets/index.html, assets/index.js, src/server.rs
=> feat: ui supports view file

README.md, src/args.rs
```diff
+ --config <config>
- --config <file>
```
=> refactor: change the value name of `--config`

src/server.rs, tests/fixtures.rs, tests/http.rs
=> fix: serve files with names containing newline char

Cargo.lock, Cargo.toml
=> fix: corrupted zip when downloading large folders

src/server.rs
Hi,
thank you for the project.
While browsing the code I stumbled over this unnecessary clone.
Sorry for this small and not really substantial MR. 
I am fine if you just close it and do it in one of another commits. 
This is just to tell you, that this clone can be removed.
Have a nice day.
=> Removes unnecessary clone

Cargo.lock, Cargo.toml, src/server.rs, tests/http.rs
=> feat: add api to get the hash of a file

src/auth.rs, src/server.rs
=> fix: strange issue that occurs only on Microsoft WebDAV

Cargo.toml, README.md, src/args.rs, src/logger.rs, src/main.rs
```
--log-file <file>      Specify the file to save logs to, other than stdout/stderr
```
close #381
=> feat: add log-file option

assets/index.css, assets/index.html, assets/index.js, tests/assets.rs, tests/fixtures.rs, tests/utils.rs
Moved all inline <script> tags out from HTML and into index.js
This was done to adhere to strict Content-Security-Policy protocols that disallow inline-scripts.
=> refactor: no inline scripts in HTML

src/server.rs, tests/http.rs
see https://github.com/sigoden/dufs/issues/414#issuecomment-2227144885
=> refactor: remove sabredav-partialupdate from DAV res header

assets/index.js
=> fix: webui unexpected save-btn when file is non-editable

src/server.rs
In dufs, if a query parameter is used as a flag, it must not accept a value.
For example, `?hash` will return the hash of the file, but `?hash=xxx` will not.
Relates to #430
=> refactor: some query params work as flag and must not accept a value

assets/index.css, assets/index.html, assets/index.js
Chrome, Edge, Firefox can logout, but Safari cannot.
close #353
=> feat: webui support logout

assets/index.js, src/auth.rs, src/server.rs, tests/auth.rs, tests/http.rs
=> refactor: make logout works on safari

CHANGELOG.md, Cargo.lock, Cargo.toml
https://github.com/sigoden/dufs/releases/tag/v0.42.0-rc1
=> chore: release v0.42.0

assets/index.js
The "0B" folder is the wrong size and distracting.
=> refactor: do not show size for Dir

assets/index.js, src/server.rs
=> feat: webui displays subdirectory items

Cargo.lock, src/args.rs, src/main.rs
```
dufs -b @dufs 
curl --abstract-unix-socket dufs http://localhost?simple
```
close #466
=> feat: support binding abstract unix socket

README.md, src/server.rs, tests/health.rs
```
$ curl http://127.0.0.1:5000/__dufs__/health
{"status":"OK"}
```
close #472
=> feat: provide healthcheck API

src/auth.rs, tests/auth.rs
=> fix: no authentication check if no auth users

assets/index.js
=> fix: webui can't handle hash property of URL well

src/server.rs
=> feat: add cache-control:no-cache while sending file and index

src/server.rs
=> fix: incorrect dir size due to hidden files

src/server.rs
A more elegant way to handle the situation of missing modified date for files.
close #554
=> feat: tolerate the absence of mtime

src/server.rs
Specifically, this will always follow symlinks when they lead to a path below the dufs root, and will follow other symlinks when `--allow-symlink` is set. This is cherry-picked and modified[^1] from #566.
(I additionally refactored some common functionality out of `zip_dir` and `handle_search_dir`.)
[^1]: Compared to the original implementation, this no longer introduces a new parameter, nor does it prevent symlinks whose target is under the dufs root from being followed when `--allow-symlink` is not set.
=> Follow symlinks when searching/archiving

src/server.rs
=> fix: unexpected public auth asking for login info

Cargo.lock, Cargo.toml, assets/index.js, src/auth.rs, src/server.rs, src/utils.rs, tests/auth.rs
- GET `?tokengen` to generate token
- GET `?token=xx` to auth
- The token is bound to the path and user.
- The token has an expiration time (currently set to 3 days).
- The token can only be used with GET requests (download only).
Close #522
=> feat: support  downloading via token auth

assets/index.js, src/server.rs, tests/auth.rs
The bug was introduced by #583.
Close #617
=> fix: login btn does not work for readonly annoymous

CHANGELOG.md, Cargo.lock, Cargo.toml
https://github.com/sigoden/dufs/releases/tag/v0.45.0-rc2
=> chore: release v0.45.0
