sigoden/dufs

Cargo.lock
Cargo.toml
README.md
src/args.rs
src/auth.rs
src/main.rs
src/server.rs

webdav do not support basic auth, so we switch to digest auth.

feat: use digest auth

---

Cargo.lock
Cargo.toml
src/server.rs

gvfs/gio doesn't like percent-encoding. Everything is ok with xml-escaped text, though.

fixed #23 filename xml escaping

---

README.md
src/args.rs
src/auth.rs
src/main.rs
src/server.rs
src/utils.rs
tests/auth.rs

Duf supports path level access control through option `--auth`/`-a`.
Grammar rule:
```
<path>@<readwrite>[@<readonly>]
```
- `<path>`: Path to protected
- `<readwrite>`: Account with readwrite permission
- `<readonly>`: Account with readonly permission
> If `<readonly>` is `*`, means `<path>` is public, everyone can acess/download it.
BREAKING CHANGE: `--auth` is changed, `--no-auth-access` is removed

feat: path level access control

---

assets/index.css
assets/index.js

fix: safari layout and compatibility

---

src/args.rs
src/server.rs
src/utils.rs

With thi pr merged, dufs allows pass glob to --hidden.
For example `dufs --hidden '.*'` will wroks. close #107 
Note:  the glob is not followd Standard Unix-style. only `?` and `*` is supported.

feat: improve hidden to support glob

---

README.md
src/args.rs
src/auth.rs
src/log_http.rs
src/main.rs
src/server.rs
tests/log_http.rs

dufs supports customize http log format via option `--log-format`.
The default format is `$remote_addr "$request" $status`.
All variables list below:
| name         | description                                                               |
| ------------ | ------------------------------------------------------------------------- |
| $remote_addr | client address                                                            |
| $remote_user | user name supplied with authentication                                    |
| $request     | full original request line                                                |
| $status      | response status                                                           |
| $http_       | arbitrary request header field. examples: $http_user_agent, $http_referer …

feat: support customize http log format

---

assets/index.css

fix: table row hover highlighting in dark mode

---

assets/index.html
src/server.rs
tests/http.rs

Submitting empty searches was calling handle_search_dir() instead of simply returning the index, returning in a blank line in the results and potentially causing hanging or crashing in large directory trees.
It may be best to also call .trim() before .is_empty() if it's felt that searching for simply whitespaces should be disabled.

fix: don't search on empty query string

---

src/server.rs
tests/webdav.rs

Per https://datatracker.ietf.org/doc/html/rfc4918#section-9.3.1,
MKCOL should return a 405 if the resource already exists.
Impetus for this change:
I am using dufs as a webdav server for [Joplin](https://joplinapp.org/)
which interpreted the previous behavior of returning a 403 as an error,
preventing syncing from working.

Fix status code for MKCOL on existing resource

---

.github/workflows/release.yaml
CHANGELOG.md
assets/index.js
src/args.rs

Found via `codespell -S target -L crate,nd`

docs: fix typos

---

README.md

Now `dufs` is in [Homebrew](https://brew.sh/)'s repository due to https://github.com/Homebrew/homebrew-core/pull/118734.
So I think the `install` instruction should be updated.

Add install instruction for Homebrew

---

src/server.rs
tests/fixtures.rs
tests/hidden.rs

A `--hidden` pattern with `/` suffix means hiding only directories not files.
A `--hidden` pattern without `/` will hide matching files and directories.
close #162

feat: hiding only directories instead of files

---

README.md
src/server.rs
tests/assets.rs
tests/fixtures.rs
tests/http.rs
tests/log_http.rs
tests/single_file.rs
tests/sort.rs
tests/symlink.rs
tests/utils.rs

use `?simple` to output path name only.
use `?json` to output paths in json format.
By default, output html page.
close #166

feat: API to search and list directories

---

src/server.rs
tests/cors.rs

cors upload `docx, excel` files need content-type

fix: cors allow-request-header add content-type

---

Cargo.lock
Cargo.toml
src/server.rs
tests/fixtures.rs
tests/http.rs

Both issue #185 and issue #105 are related to encoding.
Although it is not 100% accurate to know the encoding of a text file. 
A guess encoding is correct most of the timeis. It's better than just displaying garbled characters.

feat: guess plain text encoding then set content-type charset

---

src/server.rs
tests/http.rs

fix: URL-encoded filename when downloading in safari

---

assets/index.js

Manually tested and the displayed file size is like:
* 5.18 GB instead of 5 GB
* 1.7 GB instead of 2 GB
* 104 MB is still 104 MB
* 33 B is still 33 B

Show precise file size with two decimal places when size >= 1GB

---

Cargo.toml
src/args.rs
src/auth.rs
src/server.rs
tests/auth.rs
tests/log_http.rs
tests/single_file.rs

The access level path control used by dufs has two disadvantages:
1. One path cannot support multiple users
2. It is very troublesome to set multiple paths for one user
So it needs to be refactored.
The new auth is account based, it closes #207, closes #208.
Dufs supports account based access control. You can control who can do what on which path with `--auth`/`-a`.
```
dufs -a [user:pass]@path[:rw][,path[:rw]...][|...]
```
1: Multiple rules are separated by "|"
2: User and pass are the account name and password, if omitted, it is an anonymous user
3: One rule can set multiple paths, separated by ","
4: Add `:rw` after the path to indicate that the path has read and write permissions, otherwise the path has readonly permissions.
```
dufs -A -a admin:admin@/:rw
```
`admin` has all …

feat: new auth

---

assets/index.js

There is a situation where you can only see part of the directory before logging in, but you can see all the directories after logging in.
So it is necessary to refresh the page after successful login

fix: ui refresh page after login

---

Cargo.lock
Cargo.toml

We are already using rustls for everything else, so we might as well use rustls too for diqwest, so we don't depend on pkg-config and openssl on linux.

test: remove dependency on native tls

---

src/server.rs

This clone is not consist with the usage of `assets_prefix` in following
code and it's unnecessary.
ref：
`if let Some(name) = req_path.strip_prefix(&self.assets_prefix) {`
`.replace("__ASSETS_PREFIX__", &self.assets_prefix)`
Signed-off-by: TieWay59 <tieway59@foxmail.com>

refine: Remove one clone on `assets_prefix`

---

README.md
src/args.rs
src/auth.rs
src/log_http.rs
src/server.rs
tests/auth.rs
tests/log_http.rs

In request, we auto detect auth method from Authorization Header.
```
Basic ...        basic auth
Digest ...       digest auth
```
In response, we set a www-authenticate headers with both schema:
```
www-authenticate: Digest realm="DUFS", nonce="6544e916ba36090e25ebe3cb000be8b7d3", qop="auth", Basic realm="DUFS"
````

feat: deprecate `--auth-method`,  as both options are available

---

Cargo.lock
Cargo.toml
README.md
src/auth.rs
src/server.rs
tests/auth.rs

DUFS supports the use of sha-512 hashed password.
Create hashed password
```
$ mkpasswd  -m sha-512 -s
Password: 123456 
$6$qCAVUG7yn7t/hH4d$BWm8r5MoDywNmDP/J3V2S2a6flmKHC1IpblfoqZfuK.LtLBZ0KFXP9QIfJP8RqL8MCw4isdheoAMTuwOz.pAO/
```
Use hashed password
```
dufs -A -a 'admin:$6$qCAVUG7yn7t/hH4d$BWm8r5MoDywNmDP/J3V2S2a6flmKHC1IpblfoqZfuK.LtLBZ0KFXP9QIfJP8RqL8MCw4isdheoAMTuwOz.pAO/@/:rw'
```
Two important things for hashed passwords:
1. Dufs only supports SHA-512 hashed passwords, so ensure that the password string always starts with `$6$`.
2. Digest auth does not work with hashed passwords.

feat: support hashed password

---

README.md
src/args.rs
src/auth.rs
tests/auth.rs

Passwords can use any characters, the only restriction is that the '@/' string cannot appear.
For example `user:p|a:s@s@/:rw` is valid rule,  dufs known the pass is `p|a:s@s`.

feat: password can contain `:` `@` `|`

---

Cargo.lock
Cargo.toml
README.md
src/args.rs
src/auth.rs
src/http_logger.rs

`bind` and `hidden` are support both strings and string arrays.
```
bind: 0.0.0.0
hidden: tmp,*.log,*.lock
```
```
bind:
- 127.0.0.1
- 192.168.8.10
hidden:
- tmp
- '*.log'
- '*.lock'
```

feat: more flexible config values

---

src/server.rs
tests/http.rs

In the past, an empty search "/?q=" would return empty paths.
After this pr, an empty search "/?q=" will list all paths, just like no '?q='.

feat: empty search '?q=' list all paths

---

assets/index.js

This PR changes `addFileEntries` behaviour so that it attempts to call `readEntries` multiple times, until `readEntries` returns an empty array.
This allows `addFileEntries` to correctly handle large directories on Chromium-based browsers (`readEntries` only returns up to 100 entries per call).
Fixes #316.

fix: upload more than 100 files in directory

---

src/auth.rs
src/server.rs
tests/auth.rs

The more specific a path is, the higher its priority.
Let me take `user:pass@/dir1:rw,/dir1/test.txt` as an example:
`/dir1/test.txt` will be readonly, as `/dir1/test.txt` is more specific than `/dir1:rw`.

fix: auth precedence

---

README.md
src/auth.rs
src/server.rs
tests/auth.rs

Use `:-` to indicate that the path is forbidden.
```
dufs -a user:pass@/:rw,/dir1,/dir2:-
```
`user` has read-write permissions for `/*`, has read-only permissions for `/dir1/*`, but is fordden for `/dir2/*`.

feat: auth supports forbidden permissions

---

README.md
assets/index.css
assets/index.js
src/server.rs
tests/http.rs

HTTP PATCH support https://sabre.io/dav/http-patch/
```sh
upload_offset=$(curl -I -s http://127.0.0.1:5000/file | tr -d '\r' | sed -n 's/content-length: //p')
dd skip=$upload_offset if=file status=none ibs=1 | \
curl -X PATCH -H "X-Update-Range: append" --data-binary @- http://127.0.0.1:5000/file
```
close #335

feat: supports resumable uploads

---

README.md
src/auth.rs
src/server.rs
tests/auth.rs

#329 supports forbidden permission, but this pr reverts it.
why revert? becase many operations are anti-pattern and difficult to process. Take `/dir1:rw,/dir1/dir2:rw` as an example.
- When deleting `/dir1`, should `/dir1/dir2` be deleted?
- When moving `/dir1`, should `/dir1/dir2` be moved?
- When zip downloading `/dir1`, do you need to include `/dir1/dir2`?
- After renaming `/dir1`, the constraints of `/dir1/dir2` fail. What should I do?

feat: revert supporting for forbidden permission

---

src/server.rs

[RFC4918 (WebDAV)](https://datatracker.ietf.org/doc/html/rfc4918#section-15.7) requires the `getlastmodified` property to be a date *as returned* in a `Last-Modified` header. It also specifically references the `rfc1123-date` ABNF definition (though confusingly, as defined in [RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616#section-3.3.1)), which always ends in `GMT`.
Note that HTTP/1.1 clients must accept timestamps as Dufs currently generates them, but servers are not allowed to generate them, and thus by reference, WebDAV servers can't either.
Unfortunately, `chrono` doesn't have a `to_rfc1123` (or `to_rfc2616`) function, but all the parts are available via `format`.
I discovered this via error messages produced by the DAVx5 Android App: `dav4jvm : …

fix: timestamp format of getlastmodified in dav xml

---

assets/index.css

On macOS with Chrome, numbers rendered in the default font vary in width, resulting in misalignment and a cluttered appearance on the file list page.
This pull request addresses the issue by applying the CSS property `font-variant-numeric: tabular-nums` to the date and size fields.

refactor: add fixed-width numerals to date and size on file list page

---

assets/index.css

fix: head div overlap main contents when wrap

---

src/server.rs
tests/webdav.rs

refactor: return 400 for propfind request when depth is neither 0 nor 1

---

src/server.rs
tests/cache.rs

Hi,
this PR fixes/implements some of the HTTP conditionals like "if-modified":
- if-modified-since: was implemented
- if-unmodified-since: was not implemented
- if-none-match + etag: was implemented
- if-match + etag: was not implemented
This PR implements/fixes those conditionals and also adds some testcases for all 4.
I hope you like it.
For reference, MDN Documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since
edit: clarified "if-modified-since". I misread the code.

feat: implements remaining http cache conditionals

---

assets/index.js
src/auth.rs
src/server.rs
tests/utils.rs

When passing data using html template, its JSON content is automatically escaped for HTML entities. see #419 
```
<template id="index-data">__INDEX_DATA__</template>
```
We can use base64 to prevent such issues.

feat: base64 index-data to avoid misencoding

---

assets/index.js

> Author your commit #421 solves some problems but creates some new ones. For example, when the folder is some non-ASCII form of string, it may cause garbled problems. The root cause is that the `atob` function only accept a few ASCII characters, resulting in errors parsing strings beyond the `0xff` range.
> 
> [index.js #L111](https://github.com/sigoden/dufs/blob/ca5c3d7c541f7aa89c42db312d12e634cdc41460/assets/index.js#L111)
> 
> <img alt="image" width="884" src="https://private-user-images.githubusercontent.com/47419733/350852760-0f7d4776-186a-45fc-9df9-2b7840881510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mjg4MTksIm5iZiI6MTcyMTYyODUxOSwicGF0aCI6Ii80NzQxOTczMy8zNTA4NTI3NjAtMGY3ZDQ3 …

fix: garbled characters caused by atob

---

tests/cache.rs

This PR fixes date formatting in the tests.
Problem is, that I used "%e" formatter, which space pads the days.  
Therefore, those tests will pass on days with 2 numbers like 10.7.2024, but the tests will fail on single digit days like today 6.8.2024
This PR replaces the format with "%d" which does not space-pad the date but uses 0 pads.
ref link to the documentation: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
ref link, that 0 padding might be the way to go https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Unmodified-Since under <days>: "A 2-digit day number of the month. Examples: "04", "23"."

refactor: date formatting in cache tests

---

assets/index.js
src/auth.rs
src/server.rs
tests/auth.rs

Previously, we use `WRITEABLE <path>` for auth, which requires the user to have read-write permissions. This results in a "Forbidden" popup if the user lacks read-write permissions for the specified path.
In this PR, we use `AUTH <path` for auth, which doesn't require the user to have read-write permissions.
close #436

fix: login successed but popup `Forbidden`

---

README.md
src/auth.rs
tests/auth.rs

fix: auth failed if password contains `:`

---

src/server.rs

Since version v0.39.0 started using ReaderStream, the default buffer size is insufficient, leading to noticeable speed limitation bottlenecks in 10 Gigabit Ethernet environments.

fix: Resolve speed bottleneck in 10G network

---

CHANGELOG.md
Cargo.lock
Cargo.toml

https://github.com/sigoden/dufs/releases/tag/v0.43.0-rc1

chore: release v0.43.0

---

src/auth.rs
src/server.rs
tests/auth.rs

In `/:rw;/path1:ro`, the `/:rw` have higher perms, it shadow `/path1:ro`, so that `/path1` is granted read and write permissions.
close #519

feat: higher perm auth path shadows lower one

---

src/server.rs
src/utils.rs
tests/range.rs

This is an attempt to implement #292. I wasn't able to give a use case then, I would now say that some esoteric client implementation would be able to utilize this feature, in fact some are still doing this, for example Electron updater. Some multithreaded downloader may also use multipart ranges to reduce the fragmented range requests.

feat: implement multipart ranges

---

assets/index.js
src/server.rs

The default limit is 1000. We believe this applies to most situations.
close #553

feat: limit sub directory item counting

---

src/server.rs

Closes #576  
When a zip container is requested, make sure that "\\" is converted to "/" under windows.
It will have to effect for linux/mac.
Doc to MAIN_SEPARATOR https://doc.rust-lang.org/std/path/constant.MAIN_SEPARATOR.html

fix: incorrect separator for zip archive folders under windows

---

assets/index.html
src/main.rs
src/noscript.rs
src/server.rs
tests/http.rs

In the following cases, dufs will serve the noscript version of HTML:
- The query string contains `?noscript`
- The user-agent detects lynx, w3m, links, elinks, curl, wget, httpie, or aria2
- The browser has JavaScript disabled
Close #530

feat: support noscript fallback

---

src/utils.rs

Rust introduced with 1.89 a new warning when Lifetime elison in function signature happens. [1]
This removes the code which generate those warning.
[1] https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/#mismatched-lifetime-syntaxes-lint

chore: removes clippy warning with rust 1.89
